### ISSUE TITLE
Tarea 4 (Entrega 3): Documentación del código y pruebas

### ISSUE THREAD

**Issue by r-j28** [ISPC-TST-MOD-PROGR-2024/Visualizador-de-Temperatura-y-Humedad#12]
### Pasos sugeridos:
- Describir detalladamente el código implementado, incluyendo comentarios explicativos en cada función y módulo clave.
- Crear una guía para configurar el entorno de desarrollo y la ejecución del sistema.
- Documentar todas las pruebas realizadas, incluyendo los resultados obtenidos y los cambios que fueron necesarios.
- Subir la documentación al repositorio en un archivo README.md o en una carpeta específica de documentación.

**Comment by NicolasBa27** [comment]
[README.md](https://github.com/user-attachments/files/17267929/README.md)
